// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: spec/ErlangScanner.jflex

package miniErlang; // The generated parser will belong to this package

import miniErlang.ErlangParser.Terminals;
// The terminals are implicitly defined in the parser

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public final class ErlangScanner extends beaver.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\3\0\1\10\1\11\1\12\1\13\2\14"+
    "\1\15\1\14\1\16\1\17\1\20\11\21\2\0\1\22"+
    "\1\14\1\23\1\24\1\25\1\26\3\27\1\30\3\27"+
    "\1\31\11\27\1\32\7\27\1\33\1\14\1\34\1\0"+
    "\1\35\1\0\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\2\27\1\47\1\50\1\51\1\52"+
    "\1\53\1\27\1\54\1\55\1\56\1\57\1\60\1\61"+
    "\1\27\1\62\1\27\1\63\1\0\1\64\7\0\1\3"+
    "\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\2\12\1\13\1\14\1\15\1\16"+
    "\5\17\1\20\1\21\14\17\1\22\1\23\10\0\15\17"+
    "\1\24\10\17\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\2\0\1\17\1\33\1\34\12\17\1\35\10\17\1\36"+
    "\2\0\1\37\1\17\1\40\1\17\1\41\12\17\1\42"+
    "\1\17\1\43\1\17\2\0\3\17\1\44\2\17\1\45"+
    "\2\17\1\46\1\47\1\17\1\50\1\17\1\51\1\0"+
    "\1\52\1\17\1\53\2\17\1\54\1\17\1\55\1\17"+
    "\1\0\2\17\1\56\2\17\1\0\1\17\1\57\1\60"+
    "\1\17\1\61\1\62\1\17\1\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\65\0\152\0\65\0\237\0\65\0\324"+
    "\0\65\0\65\0\65\0\65\0\65\0\u0109\0\65\0\65"+
    "\0\65\0\65\0\u013e\0\u0173\0\u01a8\0\u01dd\0\u0212\0\65"+
    "\0\65\0\u0247\0\u027c\0\u02b1\0\u02e6\0\u031b\0\u0350\0\u0385"+
    "\0\u03ba\0\u03ef\0\u0424\0\u0459\0\u048e\0\65\0\65\0\u04c3"+
    "\0\u04f8\0\u052d\0\u0562\0\u0597\0\u05cc\0\u0601\0\u0636\0\u066b"+
    "\0\u06a0\0\u06d5\0\u070a\0\u073f\0\u0774\0\u07a9\0\u07de\0\u0813"+
    "\0\u0848\0\u087d\0\u08b2\0\u08e7\0\u0173\0\u091c\0\u0951\0\u0986"+
    "\0\u09bb\0\u09f0\0\u0a25\0\u0a5a\0\u0a8f\0\65\0\65\0\65"+
    "\0\65\0\65\0\65\0\u0ac4\0\u0af9\0\u0b2e\0\u0173\0\u0173"+
    "\0\u0b63\0\u0b98\0\u0bcd\0\u0c02\0\u0c37\0\u0c6c\0\u0ca1\0\u0cd6"+
    "\0\u0d0b\0\u0d40\0\u0173\0\u0d75\0\u0daa\0\u0ddf\0\u0e14\0\u0e49"+
    "\0\u0e7e\0\u0eb3\0\u0ee8\0\u0173\0\u0f1d\0\u0f52\0\u0173\0\u0f87"+
    "\0\u0173\0\u0fbc\0\u0173\0\u0ff1\0\u1026\0\u105b\0\u1090\0\u10c5"+
    "\0\u10fa\0\u112f\0\u1164\0\u1199\0\u11ce\0\u0173\0\u1203\0\u0173"+
    "\0\u1238\0\u126d\0\u12a2\0\u12d7\0\u130c\0\u1341\0\u0173\0\u1376"+
    "\0\u13ab\0\u0173\0\u13e0\0\u1415\0\u0173\0\u0173\0\u144a\0\u0173"+
    "\0\u147f\0\65\0\u14b4\0\u0173\0\u14e9\0\u0173\0\u151e\0\u1553"+
    "\0\u0173\0\u1588\0\u0173\0\u15bd\0\u15f2\0\u1627\0\u165c\0\u0173"+
    "\0\u1691\0\u16c6\0\u16fb\0\u1730\0\u0173\0\u0173\0\u1765\0\65"+
    "\0\u0173\0\u179a\0\u0173";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\2\1\13\1\14\1\2\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\2\1\32\1\24\1\33"+
    "\2\24\1\34\2\24\1\35\1\24\1\36\1\37\1\40"+
    "\1\24\1\41\1\42\1\43\1\44\1\45\2\24\1\46"+
    "\1\47\67\0\1\3\62\0\2\50\4\0\57\50\6\0"+
    "\1\51\5\0\1\52\2\0\1\53\2\0\1\54\3\0"+
    "\5\55\3\0\2\55\1\56\13\55\1\57\6\55\22\0"+
    "\2\16\63\0\2\24\4\0\5\24\2\0\21\24\1\60"+
    "\4\24\22\0\2\24\4\0\5\24\2\0\26\24\22\0"+
    "\2\24\4\0\5\24\2\0\14\24\1\61\11\24\22\0"+
    "\2\24\4\0\5\24\2\0\14\24\1\62\11\24\22\0"+
    "\2\24\4\0\5\24\2\0\21\24\1\63\4\24\22\0"+
    "\2\24\4\0\5\24\2\0\21\24\1\64\4\24\22\0"+
    "\2\24\4\0\5\24\2\0\1\24\1\65\10\24\1\66"+
    "\13\24\22\0\2\24\4\0\5\24\2\0\1\24\1\67"+
    "\20\24\1\70\3\24\22\0\2\24\4\0\5\24\2\0"+
    "\14\24\1\71\11\24\22\0\2\24\4\0\5\24\2\0"+
    "\1\24\1\72\13\24\1\73\10\24\22\0\2\24\4\0"+
    "\5\24\2\0\11\24\1\74\14\24\22\0\2\24\4\0"+
    "\5\24\2\0\16\24\1\75\7\24\22\0\2\24\4\0"+
    "\5\24\2\0\5\24\1\76\20\24\22\0\2\24\4\0"+
    "\5\24\2\0\16\24\1\77\2\24\1\100\4\24\22\0"+
    "\2\24\4\0\5\24\2\0\17\24\1\101\2\24\1\102"+
    "\2\24\1\103\22\0\2\24\4\0\5\24\2\0\14\24"+
    "\1\104\11\24\22\0\2\24\4\0\5\24\2\0\1\24"+
    "\1\105\24\24\2\0\7\50\1\106\55\50\11\0\1\107"+
    "\64\0\1\110\64\0\1\111\64\0\1\112\64\0\1\113"+
    "\6\0\2\55\4\0\5\55\2\0\26\55\13\0\1\113"+
    "\6\0\2\55\4\0\5\55\2\0\1\55\1\114\24\55"+
    "\13\0\1\113\6\0\2\55\4\0\5\55\2\0\5\55"+
    "\1\115\20\55\22\0\2\24\4\0\5\24\2\0\15\24"+
    "\1\116\10\24\22\0\2\24\4\0\5\24\2\0\4\24"+
    "\1\117\21\24\22\0\2\24\4\0\5\24\2\0\21\24"+
    "\1\120\4\24\22\0\2\24\4\0\5\24\2\0\17\24"+
    "\1\121\6\24\22\0\2\24\4\0\5\24\2\0\15\24"+
    "\1\122\3\24\1\123\4\24\22\0\2\24\4\0\5\24"+
    "\2\0\12\24\1\124\13\24\22\0\2\24\4\0\5\24"+
    "\2\0\1\24\1\125\24\24\22\0\2\24\4\0\5\24"+
    "\2\0\12\24\1\126\13\24\22\0\2\24\4\0\5\24"+
    "\2\0\14\24\1\127\11\24\22\0\2\24\4\0\5\24"+
    "\2\0\21\24\1\130\4\24\22\0\2\24\4\0\5\24"+
    "\2\0\21\24\1\131\4\24\22\0\2\24\4\0\5\24"+
    "\2\0\4\24\1\132\21\24\22\0\2\24\4\0\5\24"+
    "\2\0\12\24\1\133\13\24\22\0\2\24\4\0\5\24"+
    "\2\0\7\24\1\134\16\24\22\0\2\24\4\0\5\24"+
    "\2\0\1\24\1\135\24\24\22\0\2\24\4\0\5\24"+
    "\2\0\1\24\1\136\15\24\1\137\6\24\22\0\2\24"+
    "\4\0\5\24\2\0\22\24\1\140\3\24\22\0\2\24"+
    "\4\0\5\24\2\0\16\24\1\141\7\24\22\0\2\24"+
    "\4\0\5\24\2\0\16\24\1\142\7\24\22\0\2\24"+
    "\4\0\5\24\2\0\17\24\1\143\6\24\22\0\2\24"+
    "\4\0\5\24\2\0\17\24\1\144\6\24\13\0\1\113"+
    "\6\0\2\55\4\0\5\55\2\0\20\55\1\145\5\55"+
    "\13\0\1\113\6\0\2\55\4\0\5\55\2\0\3\55"+
    "\1\146\22\55\22\0\2\24\4\0\5\24\2\0\13\24"+
    "\1\147\12\24\22\0\2\24\4\0\5\24\2\0\11\24"+
    "\1\150\14\24\22\0\2\24\4\0\5\24\2\0\13\24"+
    "\1\151\12\24\22\0\2\24\4\0\5\24\2\0\17\24"+
    "\1\152\6\24\22\0\2\24\4\0\5\24\2\0\12\24"+
    "\1\153\13\24\22\0\2\24\4\0\5\24\2\0\22\24"+
    "\1\154\3\24\22\0\2\24\4\0\5\24\2\0\20\24"+
    "\1\155\5\24\22\0\2\24\4\0\5\24\2\0\3\24"+
    "\1\156\22\24\22\0\2\24\4\0\5\24\2\0\5\24"+
    "\1\157\20\24\22\0\2\24\4\0\5\24\2\0\3\24"+
    "\1\160\22\24\22\0\2\24\4\0\5\24\2\0\22\24"+
    "\1\161\3\24\22\0\2\24\4\0\5\24\2\0\11\24"+
    "\1\162\14\24\22\0\2\24\4\0\5\24\2\0\24\24"+
    "\1\163\1\24\22\0\2\24\4\0\5\24\2\0\17\24"+
    "\1\164\6\24\22\0\2\24\4\0\5\24\2\0\11\24"+
    "\1\165\14\24\22\0\2\24\4\0\5\24\2\0\5\24"+
    "\1\166\20\24\22\0\2\24\4\0\5\24\2\0\12\24"+
    "\1\167\13\24\22\0\2\24\4\0\5\24\2\0\5\24"+
    "\1\170\20\24\22\0\2\24\4\0\5\24\2\0\5\24"+
    "\1\171\20\24\13\0\1\113\6\0\2\55\4\0\5\55"+
    "\2\0\5\55\1\172\20\55\13\0\1\113\6\0\2\55"+
    "\4\0\5\55\2\0\5\55\1\173\20\55\22\0\2\24"+
    "\4\0\5\24\2\0\14\24\1\174\11\24\22\0\2\24"+
    "\4\0\5\24\2\0\11\24\1\175\14\24\22\0\2\24"+
    "\4\0\5\24\2\0\20\24\1\176\5\24\22\0\2\24"+
    "\4\0\5\24\2\0\5\24\1\177\20\24\22\0\2\24"+
    "\4\0\5\24\2\0\21\24\1\200\4\24\22\0\2\24"+
    "\4\0\5\24\2\0\7\24\1\201\16\24\22\0\2\24"+
    "\4\0\5\24\2\0\10\24\1\202\15\24\22\0\2\24"+
    "\4\0\5\24\2\0\12\24\1\203\13\24\22\0\2\24"+
    "\4\0\5\24\2\0\20\24\1\204\5\24\22\0\2\24"+
    "\4\0\5\24\2\0\14\24\1\205\11\24\22\0\2\24"+
    "\4\0\5\24\2\0\21\24\1\206\4\24\22\0\2\24"+
    "\4\0\5\24\2\0\14\24\1\207\11\24\22\0\2\24"+
    "\4\0\5\24\2\0\5\24\1\210\20\24\22\0\2\24"+
    "\4\0\5\24\2\0\7\24\1\211\16\24\13\0\1\212"+
    "\6\0\2\55\4\0\5\55\2\0\26\55\13\0\1\113"+
    "\6\0\2\55\4\0\5\55\2\0\11\55\1\213\14\55"+
    "\22\0\2\24\4\0\5\24\2\0\7\24\1\214\16\24"+
    "\22\0\2\24\4\0\5\24\2\0\2\24\1\215\23\24"+
    "\22\0\2\24\4\0\5\24\2\0\5\24\1\216\20\24"+
    "\22\0\2\24\4\0\5\24\2\0\11\24\1\217\14\24"+
    "\22\0\2\24\4\0\5\24\2\0\5\24\1\220\20\24"+
    "\22\0\2\24\4\0\5\24\2\0\5\24\1\221\20\24"+
    "\22\0\2\24\4\0\5\24\2\0\21\24\1\222\4\24"+
    "\22\0\2\24\4\0\5\24\2\0\7\24\1\223\16\24"+
    "\22\0\2\24\4\0\5\24\2\0\11\24\1\224\14\24"+
    "\13\0\1\113\6\0\2\55\4\0\5\55\2\0\23\55"+
    "\1\225\2\55\22\0\2\24\4\0\5\24\2\0\22\24"+
    "\1\226\3\24\22\0\2\24\4\0\5\24\2\0\15\24"+
    "\1\227\10\24\22\0\2\24\4\0\5\24\2\0\17\24"+
    "\1\230\6\24\22\0\2\24\4\0\5\24\2\0\5\24"+
    "\1\231\20\24\22\0\2\24\4\0\5\24\2\0\20\24"+
    "\1\232\5\24\13\0\1\113\6\0\2\55\4\0\5\55"+
    "\2\0\5\55\1\233\20\55\22\0\2\24\4\0\5\24"+
    "\2\0\21\24\1\234\4\24\22\0\2\24\4\0\5\24"+
    "\2\0\14\24\1\235\11\24\22\0\2\24\4\0\5\24"+
    "\2\0\17\24\1\236\6\24\22\0\2\24\4\0\5\24"+
    "\2\0\21\24\1\237\4\24\13\0\1\240\6\0\2\55"+
    "\4\0\5\55\2\0\26\55\22\0\2\24\4\0\5\24"+
    "\2\0\5\24\1\241\20\24\22\0\2\24\4\0\5\24"+
    "\2\0\5\24\1\242\20\24\22\0\2\24\4\0\5\24"+
    "\2\0\17\24\1\243\6\24\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6095];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\1\11\1\1\1\11\1\1\5\11"+
    "\1\1\4\11\5\1\2\11\14\1\2\11\10\0\26\1"+
    "\6\11\2\0\27\1\2\0\23\1\2\0\16\1\1\11"+
    "\1\0\11\1\1\0\5\1\1\0\4\1\1\11\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
  private beaver.Symbol sym(short id) {
    return new beaver.Symbol(id, yyline + 1, yycolumn + 1, yylength(), yytext());
  }
  private beaver.Symbol sym(short id, Object value) {
    return new beaver.Symbol(id, yyline + 1, yycolumn + 1, yylength(), value);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ErlangScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public beaver.Symbol nextToken() throws java.io.IOException, beaver.Scanner.Exception {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {     return new beaver.Symbol(Terminals.EOF, "end-of-file");
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new beaver.Scanner.Exception("illegal character \"" + yytext() + "\" at line " + yyline + "," + yycolumn);
            }
            // fall through
          case 52: break;
          case 2:
            { 
            }
            // fall through
          case 53: break;
          case 3:
            { return sym(Terminals.SESSIONSEND);
            }
            // fall through
          case 54: break;
          case 4:
            { return sym(Terminals.EXTERNALCHOICE);
            }
            // fall through
          case 55: break;
          case 5:
            { return sym(Terminals.SINGLEMARKS);
            }
            // fall through
          case 56: break;
          case 6:
            { return sym(Terminals.LQUAD);
            }
            // fall through
          case 57: break;
          case 7:
            { return sym(Terminals.RQUAD);
            }
            // fall through
          case 58: break;
          case 8:
            { return sym(Terminals.COMMA);
            }
            // fall through
          case 59: break;
          case 9:
            { return sym(Terminals.DOT);
            }
            // fall through
          case 60: break;
          case 10:
            { return sym(Terminals.INTEGER);
            }
            // fall through
          case 61: break;
          case 11:
            { return sym(Terminals.OPENANGULAR);
            }
            // fall through
          case 62: break;
          case 12:
            { return sym(Terminals.CLOSEANGULAR);
            }
            // fall through
          case 63: break;
          case 13:
            { return sym(Terminals.SESSIONRECEIVE);
            }
            // fall through
          case 64: break;
          case 14:
            { return sym(Terminals.INTERNALCHOICE);
            }
            // fall through
          case 65: break;
          case 15:
            { return sym(Terminals.IDENTIFIER);
            }
            // fall through
          case 66: break;
          case 16:
            { return sym(Terminals.LBRACKET);
            }
            // fall through
          case 67: break;
          case 17:
            { return sym(Terminals.RBRACKET);
            }
            // fall through
          case 68: break;
          case 18:
            { return sym(Terminals.LCURLYBRACE);
            }
            // fall through
          case 69: break;
          case 19:
            { return sym(Terminals.RCURLYBRACE);
            }
            // fall through
          case 70: break;
          case 20:
            { return sym(Terminals.OPERATOR);
            }
            // fall through
          case 71: break;
          case 21:
            { return sym(Terminals.STRINGVALUE);
            }
            // fall through
          case 72: break;
          case 22:
            { return sym(Terminals.SEND);
            }
            // fall through
          case 73: break;
          case 23:
            { return sym(Terminals.SYMBOL);
            }
            // fall through
          case 74: break;
          case 24:
            { return sym(Terminals.DIVISION);
            }
            // fall through
          case 75: break;
          case 25:
            { return sym(Terminals.LESS);
            }
            // fall through
          case 76: break;
          case 26:
            { return sym(Terminals.ATOMID);
            }
            // fall through
          case 77: break;
          case 27:
            { return sym(Terminals.END);
            }
            // fall through
          case 78: break;
          case 28:
            { return sym(Terminals.INTTYPE);
            }
            // fall through
          case 79: break;
          case 29:
            { return sym(Terminals.NULL);
            }
            // fall through
          case 80: break;
          case 30:
            { return sym(Terminals.VAR);
            }
            // fall through
          case 81: break;
          case 31:
            { return sym(Terminals.ATOMTYPE);
            }
            // fall through
          case 82: break;
          case 32:
            { return sym(Terminals.ATOM);
            }
            // fall through
          case 83: break;
          case 33:
            { return sym(Terminals.CALL);
            }
            // fall through
          case 84: break;
          case 34:
            { return sym(Terminals.TRUE);
            }
            // fall through
          case 85: break;
          case 35:
            { return sym(Terminals.TYPE);
            }
            // fall through
          case 86: break;
          case 36:
            { return sym(Terminals.FALSE);
            }
            // fall through
          case 87: break;
          case 37:
            { return sym(Terminals.MATCH);
            }
            // fall through
          case 88: break;
          case 38:
            { return sym(Terminals.SPAWN);
            }
            // fall through
          case 89: break;
          case 39:
            { return sym(Terminals.START);
            }
            // fall through
          case 90: break;
          case 40:
            { return sym(Terminals.TUPLE);
            }
            // fall through
          case 91: break;
          case 41:
            { return sym(Terminals.CASE);
            }
            // fall through
          case 92: break;
          case 42:
            { return sym(Terminals.STRINGTYPE);
            }
            // fall through
          case 93: break;
          case 43:
            { return sym(Terminals.CLAUSE);
            }
            // fall through
          case 94: break;
          case 44:
            { return sym(Terminals.MODULE);
            }
            // fall through
          case 95: break;
          case 45:
            { return sym(Terminals.STRING);
            }
            // fall through
          case 96: break;
          case 46:
            { return sym(Terminals.INT);
            }
            // fall through
          case 97: break;
          case 47:
            { return sym(Terminals.FUNCTION);
            }
            // fall through
          case 98: break;
          case 48:
            { return sym(Terminals.REGISTER);
            }
            // fall through
          case 99: break;
          case 49:
            { return sym(Terminals.RECEIVE);
            }
            // fall through
          case 100: break;
          case 50:
            { return sym(Terminals.ATTRIBUTE);
            }
            // fall through
          case 101: break;
          case 51:
            { return sym(Terminals.UNREGISTER);
            }
            // fall through
          case 102: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
