// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: spec/ErlangScanner.jflex

package miniErlang; // The generated parser will belong to this package

import miniErlang.ErlangParser.Terminals;
// The terminals are implicitly defined in the parser

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public final class ErlangScanner extends beaver.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\6"+
    "\1\7\1\10\4\0\1\11\2\0\2\12\1\13\1\12"+
    "\1\0\1\12\1\14\11\15\2\0\2\12\3\0\32\16"+
    "\1\17\1\12\1\20\1\0\1\21\1\0\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\2\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\33\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\33\1\47\1\33\1\50"+
    "\1\0\1\51\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\1\1\4\1\5\1\6"+
    "\2\7\1\10\1\11\1\12\13\10\1\13\1\14\5\0"+
    "\11\10\1\15\7\10\1\16\1\17\1\20\2\0\12\10"+
    "\1\21\7\10\1\22\2\0\1\23\1\10\1\24\1\25"+
    "\12\10\1\26\1\10\1\27\2\0\2\10\1\30\2\10"+
    "\1\31\2\10\1\32\1\33\1\10\1\34\1\25\1\0"+
    "\1\10\1\35\2\10\1\36\1\10\1\37\1\0\2\10"+
    "\1\40\1\10\1\0\1\10\1\41\1\42\1\43\1\44";

  private static int [] zzUnpackAction() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\52\0\124\0\52\0\176\0\250\0\52"+
    "\0\52\0\52\0\322\0\374\0\52\0\52\0\u0126\0\u0150"+
    "\0\u017a\0\u01a4\0\u01ce\0\u01f8\0\u0222\0\u024c\0\u0276\0\u02a0"+
    "\0\u02ca\0\52\0\52\0\u02f4\0\u031e\0\u0348\0\u0372\0\u039c"+
    "\0\u03c6\0\u03f0\0\u041a\0\u0444\0\u046e\0\u0498\0\u04c2\0\u04ec"+
    "\0\u0516\0\374\0\u0540\0\u056a\0\u0594\0\u05be\0\u05e8\0\u0612"+
    "\0\u063c\0\52\0\52\0\52\0\u0666\0\u0690\0\u06ba\0\u06e4"+
    "\0\u070e\0\u0738\0\u0762\0\u078c\0\u07b6\0\u07e0\0\u080a\0\u0834"+
    "\0\374\0\u085e\0\u0888\0\u08b2\0\u08dc\0\u0906\0\u0930\0\u095a"+
    "\0\374\0\u0984\0\u09ae\0\374\0\u09d8\0\374\0\374\0\u0a02"+
    "\0\u0a2c\0\u0a56\0\u0a80\0\u0aaa\0\u0ad4\0\u0afe\0\u0b28\0\u0b52"+
    "\0\u0b7c\0\374\0\u0ba6\0\374\0\u0bd0\0\u0bfa\0\u0c24\0\u0c4e"+
    "\0\374\0\u0c78\0\u0ca2\0\374\0\u0ccc\0\u0cf6\0\374\0\374"+
    "\0\u0d20\0\374\0\52\0\u0d4a\0\u0d74\0\374\0\u0d9e\0\u0dc8"+
    "\0\374\0\u0df2\0\374\0\u0e1c\0\u0e46\0\u0e70\0\374\0\u0e9a"+
    "\0\u0ec4\0\u0eee\0\374\0\374\0\52\0\374";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\3\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\2\1\17\1\14\1\20\2\14\1\21\2\14\1\22"+
    "\2\14\1\23\1\24\1\25\1\14\1\26\1\27\1\30"+
    "\1\14\1\31\2\14\1\32\1\33\54\0\1\3\47\0"+
    "\2\34\4\0\44\34\16\0\1\35\3\0\2\36\1\37"+
    "\14\36\1\40\6\36\16\0\2\13\50\0\3\14\2\0"+
    "\27\14\16\0\3\14\2\0\22\14\1\41\4\14\16\0"+
    "\3\14\2\0\1\14\1\42\11\14\1\43\13\14\16\0"+
    "\3\14\2\0\1\14\1\44\21\14\1\45\3\14\16\0"+
    "\3\14\2\0\15\14\1\46\11\14\16\0\3\14\2\0"+
    "\1\14\1\47\14\14\1\50\10\14\16\0\3\14\2\0"+
    "\11\14\1\51\15\14\16\0\3\14\2\0\17\14\1\52"+
    "\7\14\16\0\3\14\2\0\5\14\1\53\21\14\16\0"+
    "\3\14\2\0\17\14\1\54\2\14\1\55\4\14\16\0"+
    "\3\14\2\0\20\14\1\56\2\14\1\57\2\14\1\60"+
    "\16\0\3\14\2\0\1\14\1\61\25\14\2\0\10\34"+
    "\1\62\41\34\11\0\1\63\2\0\3\35\2\0\27\35"+
    "\10\0\1\36\2\0\1\64\2\0\3\36\2\0\27\36"+
    "\10\0\1\36\2\0\1\64\2\0\3\36\2\0\1\36"+
    "\1\65\25\36\10\0\1\36\2\0\1\64\2\0\3\36"+
    "\2\0\5\36\1\66\21\36\16\0\3\14\2\0\16\14"+
    "\1\67\3\14\1\70\4\14\16\0\3\14\2\0\13\14"+
    "\1\71\5\14\1\72\5\14\16\0\3\14\2\0\1\14"+
    "\1\73\25\14\16\0\3\14\2\0\13\14\1\74\13\14"+
    "\16\0\3\14\2\0\15\14\1\75\11\14\16\0\3\14"+
    "\2\0\22\14\1\76\4\14\16\0\3\14\2\0\22\14"+
    "\1\77\4\14\16\0\3\14\2\0\4\14\1\100\22\14"+
    "\16\0\3\14\2\0\13\14\1\101\13\14\16\0\3\14"+
    "\2\0\7\14\1\102\17\14\16\0\3\14\2\0\1\14"+
    "\1\103\25\14\16\0\3\14\2\0\1\14\1\104\16\14"+
    "\1\105\6\14\16\0\3\14\2\0\23\14\1\106\3\14"+
    "\16\0\3\14\2\0\17\14\1\107\7\14\16\0\3\14"+
    "\2\0\17\14\1\110\7\14\16\0\3\14\2\0\20\14"+
    "\1\111\6\14\10\0\1\36\2\0\1\64\2\0\3\36"+
    "\2\0\21\36\1\112\5\36\10\0\1\36\2\0\1\64"+
    "\2\0\3\36\2\0\3\36\1\113\23\36\16\0\3\14"+
    "\2\0\14\14\1\114\12\14\16\0\3\14\2\0\20\14"+
    "\1\115\6\14\16\0\3\14\2\0\13\14\1\116\13\14"+
    "\16\0\3\14\2\0\5\14\1\117\21\14\16\0\3\14"+
    "\2\0\23\14\1\120\3\14\16\0\3\14\2\0\21\14"+
    "\1\121\5\14\16\0\3\14\2\0\3\14\1\122\23\14"+
    "\16\0\3\14\2\0\5\14\1\123\21\14\16\0\3\14"+
    "\2\0\3\14\1\124\23\14\16\0\3\14\2\0\23\14"+
    "\1\125\3\14\16\0\3\14\2\0\11\14\1\126\15\14"+
    "\16\0\3\14\2\0\25\14\1\127\1\14\16\0\3\14"+
    "\2\0\20\14\1\130\6\14\16\0\3\14\2\0\11\14"+
    "\1\131\15\14\16\0\3\14\2\0\5\14\1\132\21\14"+
    "\16\0\3\14\2\0\13\14\1\133\13\14\16\0\3\14"+
    "\2\0\5\14\1\134\21\14\10\0\1\36\2\0\1\64"+
    "\2\0\3\36\2\0\5\36\1\135\21\36\10\0\1\36"+
    "\2\0\1\64\2\0\3\36\2\0\5\36\1\136\21\36"+
    "\16\0\3\14\2\0\11\14\1\137\15\14\16\0\3\14"+
    "\2\0\21\14\1\140\5\14\16\0\3\14\2\0\5\14"+
    "\1\141\21\14\16\0\3\14\2\0\22\14\1\142\4\14"+
    "\16\0\3\14\2\0\7\14\1\143\17\14\16\0\3\14"+
    "\2\0\10\14\1\144\16\14\16\0\3\14\2\0\13\14"+
    "\1\145\13\14\16\0\3\14\2\0\21\14\1\146\5\14"+
    "\16\0\3\14\2\0\15\14\1\147\11\14\16\0\3\14"+
    "\2\0\22\14\1\150\4\14\16\0\3\14\2\0\15\14"+
    "\1\151\11\14\16\0\3\14\2\0\5\14\1\152\21\14"+
    "\10\0\1\36\2\0\1\153\2\0\3\36\2\0\27\36"+
    "\10\0\1\36\2\0\1\64\2\0\3\36\2\0\11\36"+
    "\1\154\15\36\16\0\3\14\2\0\2\14\1\155\24\14"+
    "\16\0\3\14\2\0\5\14\1\156\21\14\16\0\3\14"+
    "\2\0\11\14\1\157\15\14\16\0\3\14\2\0\5\14"+
    "\1\160\21\14\16\0\3\14\2\0\5\14\1\161\21\14"+
    "\16\0\3\14\2\0\22\14\1\162\4\14\16\0\3\14"+
    "\2\0\7\14\1\163\17\14\10\0\1\36\2\0\1\64"+
    "\2\0\3\36\2\0\24\36\1\164\2\36\16\0\3\14"+
    "\2\0\23\14\1\165\3\14\16\0\3\14\2\0\16\14"+
    "\1\166\10\14\16\0\3\14\2\0\20\14\1\167\6\14"+
    "\16\0\3\14\2\0\5\14\1\170\21\14\10\0\1\36"+
    "\2\0\1\64\2\0\3\36\2\0\5\36\1\171\21\36"+
    "\16\0\3\14\2\0\22\14\1\172\4\14\16\0\3\14"+
    "\2\0\15\14\1\173\11\14\16\0\3\14\2\0\20\14"+
    "\1\174\6\14\10\0\1\36\2\0\1\175\2\0\3\36"+
    "\2\0\27\36\16\0\3\14\2\0\5\14\1\176\21\14"+
    "\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3864];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\1\11\2\1\3\11\2\1\2\11"+
    "\13\1\2\11\5\0\21\1\3\11\2\0\23\1\2\0"+
    "\21\1\2\0\14\1\1\11\1\0\7\1\1\0\4\1"+
    "\1\0\3\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
  private beaver.Symbol sym(short id) {
    return new beaver.Symbol(id, yyline + 1, yycolumn + 1, yylength(), yytext());
  }
  private beaver.Symbol sym(short id, Object value) {
    return new beaver.Symbol(id, yyline + 1, yycolumn + 1, yylength(), value);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ErlangScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public beaver.Symbol nextToken() throws java.io.IOException, beaver.Scanner.Exception {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {     return new beaver.Symbol(Terminals.EOF, "end-of-file");
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new beaver.Scanner.Exception("illegal character \"" + yytext() + "\" at line " + yyline + "," + yycolumn);
            }
            // fall through
          case 37: break;
          case 2:
            { 
            }
            // fall through
          case 38: break;
          case 3:
            { return sym(Terminals.SEND);
            }
            // fall through
          case 39: break;
          case 4:
            { return sym(Terminals.SINGLEMARKS);
            }
            // fall through
          case 40: break;
          case 5:
            { return sym(Terminals.SYMBOL);
            }
            // fall through
          case 41: break;
          case 6:
            { return sym(Terminals.COMMA);
            }
            // fall through
          case 42: break;
          case 7:
            { return sym(Terminals.INTEGER);
            }
            // fall through
          case 43: break;
          case 8:
            { return sym(Terminals.IDENTIFIER);
            }
            // fall through
          case 44: break;
          case 9:
            { return sym(Terminals.LBRACKET);
            }
            // fall through
          case 45: break;
          case 10:
            { return sym(Terminals.RBRACKET);
            }
            // fall through
          case 46: break;
          case 11:
            { return sym(Terminals.LCURLYBRACE);
            }
            // fall through
          case 47: break;
          case 12:
            { return sym(Terminals.RCURLYBRACE);
            }
            // fall through
          case 48: break;
          case 13:
            { return sym(Terminals.OPERATOR);
            }
            // fall through
          case 49: break;
          case 14:
            { return sym(Terminals.STRINGVALUE);
            }
            // fall through
          case 50: break;
          case 15:
            { return sym(Terminals.VARIABLEID);
            }
            // fall through
          case 51: break;
          case 16:
            { return sym(Terminals.ATOMID);
            }
            // fall through
          case 52: break;
          case 17:
            { return sym(Terminals.NULL);
            }
            // fall through
          case 53: break;
          case 18:
            { return sym(Terminals.VAR);
            }
            // fall through
          case 54: break;
          case 19:
            { return sym(Terminals.ATOM);
            }
            // fall through
          case 55: break;
          case 20:
            { return sym(Terminals.CALL);
            }
            // fall through
          case 56: break;
          case 21:
            { return sym(Terminals.CASE);
            }
            // fall through
          case 57: break;
          case 22:
            { return sym(Terminals.TRUE);
            }
            // fall through
          case 58: break;
          case 23:
            { return sym(Terminals.TYPE);
            }
            // fall through
          case 59: break;
          case 24:
            { return sym(Terminals.FALSE);
            }
            // fall through
          case 60: break;
          case 25:
            { return sym(Terminals.MATCH);
            }
            // fall through
          case 61: break;
          case 26:
            { return sym(Terminals.SPAWN);
            }
            // fall through
          case 62: break;
          case 27:
            { return sym(Terminals.START);
            }
            // fall through
          case 63: break;
          case 28:
            { return sym(Terminals.TUPLE);
            }
            // fall through
          case 64: break;
          case 29:
            { return sym(Terminals.CLAUSE);
            }
            // fall through
          case 65: break;
          case 30:
            { return sym(Terminals.MODULE);
            }
            // fall through
          case 66: break;
          case 31:
            { return sym(Terminals.STRING);
            }
            // fall through
          case 67: break;
          case 32:
            { return sym(Terminals.INTTYPE);
            }
            // fall through
          case 68: break;
          case 33:
            { return sym(Terminals.FUNCTION);
            }
            // fall through
          case 69: break;
          case 34:
            { return sym(Terminals.REGISTER);
            }
            // fall through
          case 70: break;
          case 35:
            { return sym(Terminals.RECEIVE);
            }
            // fall through
          case 71: break;
          case 36:
            { return sym(Terminals.ATTRIBUTE);
            }
            // fall through
          case 72: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
