@startuml
'https://plantuml.com/component-diagram

skinparam componentStyle rectangle
skinparam interfaceFontSize 30
skinparam arrowFontSize 30
skinparam noteFontSize 30
skinparam rectangleBorderThickness 1
skinparam nodeFontStyle bold

skinparam cloud{
  FontSize 30
}
skinparam rectangle{
  FontSize 30
}


rectangle "Erlang_Code"{
note as C
Client.erl, Seller.erl, Main.erl, Bank.erl, .global
end note
}

rectangle "Erlang_Abstract_Format"{
note as C_
Client.erl, Seller.erl, Bank.erl
end note

}

Erlang_Code --> Erlang_Abstract_Format
Erlang_Code --> Global
rectangle "Program"
rectangle "Global"{
        [client->seller:title<String>...]
}

rectangle Program

Erlang_Abstract_Format -> Program

rectangle "Session"{
    [Client]
    [Seller]
    [Bank]
}

rectangle "Session_"{
    [Client']
    [Seller']
    [Bank']
}

Global ---> Session:projection
Program --> Session_:type inference

Session --> isSubtype
Session_ --> isSubtype

@enduml