@startuml
'https://plantuml.com/component-diagram
skinparam classFontName Courier
skinparam componentStyle rectangle
skinparam componentFontName Courier
skinparam rectangleFontName Courier
skinparam circledCharacterFontName Courier
skinparam arrowFontName Courier
skinparam component {
  FontSize 20
  FontName Courier
}

skinparam cloud{
  FontSize 20
  FontName Courier
}

skinparam node{
  FontSize 20
  FontName Courier
}

node "Erlang code"{
    [Client.erl]
    [Seller.erl]
    [Main.erl]
    [Bank.erl]
    [.global]
}

node "Erlang Abstract Format"{
    [Client.form]
    [Seller.form]
    [Bank.form]
}

[Bank.erl] --> [Bank.form]
[Seller.erl] -> [Seller.form]
[Client.erl] -> [Client.form]

cloud "Program"
cloud "Global"{
    client->seller:title<String>...
}

[Client.form] --> Program
[Seller.form] --> Program:parse
[Bank.form] --> Program
[.global] --> Global:parse

cloud "Session"{
    [Client]
    [Seller]
    [Bank]
}

cloud "SessionDerived"{
    [ClientDerived]
    [SellerDerived]
    [BankDerived]
}

Global --> Session:projection
Program --> SessionDerived:type inference

Session --> isSubtype:projection type
SessionDerived --> isSubtype:code type

@enduml