@startuml
'https://plantuml.com/component-diagram
skinparam componentStyle rectangle
skinparam rectangleFontSize 30
skinparam noteFontSize 30
skinparam arrowFontSize 25
skinparam arrowFontSize 25
skinparam interfaceFontSize 25

rectangle "Erlang code"{
    [Client.erl]
    [Seller.erl]
    [Main.erl]
    [Bank.erl]
    [.global]
}

rectangle "Erlang Abstract Format"{
    [Client.form]
    [Seller.form]
    [Bank.form]
}

[Bank.erl] --> [Bank.form]
[Seller.erl] -> [Seller.form]
[Client.erl] -> [Client.form]

rectangle "Program"
rectangle "Global"{
    note as G
    client->seller:title<String>...
    end note
}

[Client.form] --> Program
[Seller.form] -> Program:parse
[Bank.form] -> Program
[.global] -> Global:parse

rectangle "Session"{
[Client]
[Seller]
[Bank]
}

rectangle "Session Inferred" as SessionDerived{
[Client']
[Seller']
[Bank']
}

Global --> Session:projection
Program --> SessionDerived:type inference

Session --> isSubtype
SessionDerived --> isSubtype

@enduml