@startuml
'https://plantuml.com/class-diagram

class Function

class Function {
}

Function -- Function:getFunctions()

abstract class Process{
}

class Module{
}

class FunType{
}

class Receive{
}
class Case{
}

class ExpressionProcess
abstract class Expression{
}

Module "1" *-- "n" Function:getFunctions()
Function  --  Process: getBody()
Session -- Function: getInferredType()
FunType - Function: type()
ExpressionProcess - Expression
Process <|--- Send
Process <|--- Register
Process <|--- Unregister
Process <|-- Receive
Process <|-- Case
Process <|-- Let
Process <|- ExpressionProcess

class Operator{

}

class Call{

}

Operator --|> Expression
Expression <|- Self
Expression <|-- Call
abstract Pattern
Pattern --|> Expression


class ReceiveClause{
}
class CaseClause{

}

Receive "1" *-- "n" ReceiveClause
Case "1" *-- "n" CaseClause

class Delegating {
}

Delegating - Process:delegating()

@enduml