@startuml
    note as n
        implementazione dei protocolli
    end note
    n-.Erlang
    node Erlang{

    }

    note as nk
        - implementazione parsing
        - implementazione proiezione
        - implementazione type-checking
    end note
    nk-.JASTADD
    node JASTADD{

    }

    JASTADD --> antr
    note as c
        gestore della build:
        - generazione del parser
        - generazione delle classi AST
        - compilazione sorgenti java generati
    end note
    antr.c
    node antr{

    }

    Erlang <- Java
    Java --> antr

    note as j
        - compilazione erlang tramite
          chiamate di sistema
        - avvio della fase di parsing
        - avvio della fase type-checking
    end note
    Java.j
    node Java{
    }

    rectangle jar
    antr --> jar



@enduml