@startuml
    note as n
        implementazione dei protocolli
    end note
    n-.Erlang
    node Erlang{

    }

    note as nk
        - implementazione parsing
        - implementazione proiezione
        - implementazione type-checking
    end note
    nk-.JASTADD
    node JASTADD{

    }

    JASTADD ---> ant
    note as c
        gestore della build:
        - generazione del parser
        - generazione classi java AST
        - compilazione sorgenti java generati
    end note
    ant.c
    node ant{

    }

    Erlang --> Java:input
    Java --> ant

    note as j
        - compilazione erlang tramite
          chiamate di sistema
        - avvio della fase di parsing
        - avvio della fase type-checking
    end note
    Java.j
    node Java{
    }

    rectangle jar
    ant --> jar

@enduml